spring.application.name=airBnbApp

#DB Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/airBnb
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.datasource.username=sagaryadav
spring.datasource.password=root1234
server.servlet.context-path=/api/v1
jwt.secretKey=a8sd6faihdfjkas2398789afhdskjasdfh87yhk3jha987sdf89aabsdf876

frontend.url=http://localhost:8080
stripe.secret.key=sk_test_51UISFIQDWDpAfdxZHn6yxXZn9GvvrQ3renyE2zXXYsFzKkIxuUNMbIuQibDdMfRSiPuAynP7oisesHnwObs2od4k009DiPJsL9
stripe.webhook.secret=whsec_6175e2d6b06a8c17a1c9acb3d055a773500a7e28a0b472bc412b00dcd807b1e5